"""add celery_task_id and cancel_requested to jobs

Revision ID: 30353b54044b
Revises: 
Create Date: 2026-09-20 17:26:55.758229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '30353b54044b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_steps', sa.Column('celery_task_id', sa.Text(), nullable=True))
    op.add_column('job_steps', sa.Column('cancel_requested', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('jobs', sa.Column('celery_task_id', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('cancel_requested', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cancel_requested')
    op.drop_column('jobs', 'celery_task_id')
    op.drop_column('job_steps', 'cancel_requested')
    op.drop_column('job_steps', 'celery_task_id')
    # ### end Alembic commands ###