"""add_email_body_and_provider_message_id

Revision ID: 32d37e9a6889
Revises: eb7d869081f9
Create Date: 2026-10-01 12:15:53.111167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '32d37e9a6889'
down_revision: Union[str, Sequence[str], None] = 'eb7d869081f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('provider_message_id', sa.Text(), nullable=True))
    op.add_column('emails', sa.Column('body', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'body')
    op.drop_column('emails', 'provider_message_id')
    # ### end Alembic commands ###
