"""fix export model fields

Revision ID: eb7d869081f9
Revises: 33a27e75848d
Create Date: 2026-10-01 09:16:26.568333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'eb7d869081f9'
down_revision: Union[str, Sequence[str], None] = '33a27e75848d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exports', sa.Column('status', sa.Text(), nullable=False))
    op.add_column('exports', sa.Column('file_url', sa.Text(), nullable=True))
    op.add_column('exports', sa.Column('row_count', sa.Integer(), nullable=True))
    op.add_column('exports', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('exports', 'storage_path')
    op.drop_column('exports', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exports', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('exports', sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('exports', 'completed_at')
    op.drop_column('exports', 'row_count')
    op.drop_column('exports', 'file_url')
    op.drop_column('exports', 'status')
    # ### end Alembic commands ###